apiVersion: v1
kind: Service
metadata:
  labels:
    name: cart
  name: cart
spec:
  ports:
    - name: "5006"
      port: 5006
      targetPort: 5006
  selector:
    name: cart
  type: LoadBalancer
status:
  loadBalancer: {}
