apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cart
  name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cart
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cart
    spec:
      containers:
        - env:
            - name: AUTH_PROVIDER_X509_CERT_URL
            - name: AUTH_URI
            - name: CLIENT_EMAIL
            - name: CLIENT_ID
            - name: CLIENT_X509_CERT_URL
            - name: PRIVATE_KEY
            - name: PRIVATE_KEY_ID
            - name: PROJECT_ID
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: TOKEN_URI
            - name: TYPE
          image: lingliyin/cart:v1
          name: cart
          ports:
            - containerPort: 5006
          resources: {}
      restartPolicy: Always
status: {}
