apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cart
  name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cart
  strategy: {}
  template:
    metadata:
      labels:
        name: cart
    spec:
      containers:
        - image: gcr.io/elegant-fort-344208/cart:v1
          name: cart
          ports:
            - containerPort: 5006
          resources: {}
      restartPolicy: Always
status: {}
