version: "3.8"

services:
 
  ###################################
  # Product: The Product microservice
  ###################################
  product:
    build:
      context: ./app/product_service
      dockerfile: Dockerfile
    image: lingliyin/product:v1
    restart: always
    environment:
      TYPE: ${TYPE}
      PROJECT_ID: ${PROJECT_ID}
      PRIVATE_KEY_ID: ${PRIVATE_KEY_ID}
      PRIVATE_KEY: ${PRIVATE_KEY}
      CLIENT_EMAIL: ${CLIENT_EMAIL}
      CLIENT_ID: ${CLIENT_ID}
      AUTH_URI: ${AUTH_URI}
      TOKEN_URI: ${TOKEN_URI}
      AUTH_PROVIDER_X509_CERT_URL: ${AUTH_PROVIDER_X509_CERT_URL}
      CLIENT_X509_CERT_URL: ${CLIENT_X509_CERT_URL}
      PYTHONUNBUFFERED: 1
    ports:
      - "5005:5005"
 
  #######################################################
  # Cart: The Cart microservice
  #######################################################
  cart:
    build:
      context: ./app/cart_service
      dockerfile: Dockerfile
    image: lingliyin/cart:v1
    restart: always
    environment:
      TYPE: ${TYPE}
      PROJECT_ID: ${PROJECT_ID}
      PRIVATE_KEY_ID: ${PRIVATE_KEY_ID}
      PRIVATE_KEY: ${PRIVATE_KEY}
      CLIENT_EMAIL: ${CLIENT_EMAIL}
      CLIENT_ID: ${CLIENT_ID}
      AUTH_URI: ${AUTH_URI}
      TOKEN_URI: ${TOKEN_URI}
      AUTH_PROVIDER_X509_CERT_URL: ${AUTH_PROVIDER_X509_CERT_URL}
      CLIENT_X509_CERT_URL: ${CLIENT_X509_CERT_URL}
      PYTHONUNBUFFERED: 1
    ports:
      - "5006:5006"
      
  #################################################
  # Order: The Order microservice
  #################################################
  order:
    build:
      context: ./app/order_service
      dockerfile: Dockerfile
    image: lingliyin/order:v1
    restart: always
    environment:
      PASSWORD: ${PASSWORD}
      PUBLIC_IP_ADDRESS: ${PUBLIC_IP_ADDRESS}
      DBNAME: ${DBNAME}
      PROJECT_ID: ${PROJECT_ID}
      INSTANCE_NAME: ${INSTANCE_NAME}
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"

  ###################################
  # Payment: The Payment microservice
  ###################################
  payment:
    build:
      context: ./app/payment_service
      dockerfile: Dockerfile
    image: lingliyin/payment:v1
    restart: always
    environment:
      apikey: ${apikey}
      PYTHONUNBUFFERED: 1
    ports:
      - "4242:4242"

  ###############################################
  # Stock: The Stock microservice
  ###############################################
  stock:
    build:
      context: ./app/stock_service
      dockerfile: Dockerfile
    image: lingliyin/stock:v1
    restart: always
    environment:
      PASSWORD: ${PASSWORD}
      PUBLIC_IP_ADDRESS: ${PUBLIC_IP_ADDRESS}
      DBNAME: ${DBNAME}
      PROJECT_ID: ${PROJECT_ID}
      INSTANCE_NAME: ${INSTANCE_NAME}
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"

  ##################################
  # Users: The Users microservice
  ##################################
  users:
    build:
      context: ./app/users_service
      dockerfile: Dockerfile
    image: lingliyin/users:v1
    restart: always
    environment:
      PASSWORD: ${PASSWORD}
      PUBLIC_IP_ADDRESS: ${PUBLIC_IP_ADDRESS}
      DBNAME: ${DBNAME}
      PROJECT_ID: ${PROJECT_ID}
      INSTANCE_NAME: ${INSTANCE_NAME}
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"
