version: "3.8"

services:

  ##################################
  # Users: The Users microservice
  ##################################
  users:
    build:
      context: ./app/users_service
      dockerfile: Dockerfile
    image: gcr.io/elegant-fort-344208/users:v1
    restart: always
    ports:
      - "5003:5003"

  ###################################
  # Cart: The Cart microservice
  ###################################
  cart:
    build:
      context: ./app/cart_service
      dockerfile: Dockerfile
    image: gcr.io/elegant-fort-344208/cart:v1
    restart: always
    ports:
      - "5006:5006"

  # ##################################
  # Product: The Product microservice
  # ##################################
  product:
    build:
      context: ./app/product_service
      dockerfile: Dockerfile
    image: gcr.io/elegant-fort-344208/product:v1
    restart: always
    ports:
      - "5005:5005"

  ###################################
  # Payment: The Payment microservice
  ###################################
  payment:
    build:
      context: ./app/payment_service
      dockerfile: Dockerfile
    image: gcr.io/elegant-fort-344208/payment:v1
    restart: always
    ports:
      - "4242:4242"

  #################################################
  # Order: The Order microservice
  #################################################
  order:
    build:
      context: ./app/order_service
      dockerfile: Dockerfile
    image: gcr.io/elegant-fort-344208/order:v1
    restart: always
    ports:
      - "5000:5000"

  ###############################################
  # Stock: The Stock microservice
  ###############################################
  stock:
    build:
      context: ./app/stock_service
      dockerfile: Dockerfile
    image: gcr.io/elegant-fort-344208/stock:v1
    restart: always
    ports:
      - "5001:5001"

  ###############################################
  # Stock-PubSub: The Stock microservice
  ###############################################
  stock-pubsub:
    build:
      context: ./app/stock_subscriber
      dockerfile: Dockerfile
    image: gcr.io/elegant-fort-344208/stock-pubsub:v1
    restart: always

  ###############################################
  # Order-PubSub: The Order microservice
  ###############################################
  order-pubsub:
    build:
      context: ./app/order_subscriber
      dockerfile: Dockerfile
    image: gcr.io/elegant-fort-344208/order-pubsub:v1
    restart: always