version: "3.8"

services:
 
  ###################################
  # Product: The Product microservice
  ###################################
  product:
    build:
      context: ./
      dockerfile: product.Dockerfile
    image: jingweisim/product:v1
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5005:5005"
 
  #######################################################
  # Cart: The Cart microservice
  #######################################################
  cart:
    build:
      context: ./
      dockerfile: cart.Dockerfile
    image: jingweisim/cart:v1
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5006:5006"
      
  #################################################
  # Order: The Order microservice
  #################################################
  order:
    build:
      context: ./
      dockerfile: order.Dockerfile
    image: jingweisim/order:v1
    restart: always
    environment:
      dbURL: ${dbURL}
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"

  ###################################
  # Payment: The Payment microservice
  ###################################
  payment:
    build:
      context: ./
      dockerfile: payment.Dockerfile
    image: jingweisim/payment:v1
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "4242:4242"

  ###############################################
  # Stock: The Stock microservice
  ###############################################
  stock:
    build:
      context: ./
      dockerfile: stock.Dockerfile
    image: jingweisim/stock:v1
    restart: always
    environment:
      dbURL: ${dbURL}
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"

  ##################################
  # Users: The Users microservice
  ##################################
  users:
    build:
      context: ./
      dockerfile: users.Dockerfile
    image: jingweisim/users:v1
    restart: always
    environment:
      dbURL: ${dbURL}
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"
