version: "3.8"

services:
 
  ###################################
  # Product: The Product microservice
  ###################################
  product:
    build:
      context: ./app/product_service
      dockerfile: Dockerfile
    image: gcr.io/elegant-fort-344208/product:v1
    restart: always
    ports:
      - "5005:5005"
    labels:
      kompose.service.type: LoadBalancer

  #######################################################
  # Cart: The Cart microservice
  #######################################################
  cart:
    build:
      context: ./app/cart_service
      dockerfile: Dockerfile
    image: gcr.io/elegant-fort-344208/cart:v1
    restart: always
    ports:
      - "5006:5006"
    labels:
      kompose.service.type: LoadBalancer

  #################################################
  # Order: The Order microservice
  #################################################
  order:
    build:
      context: ./app/order_service
      dockerfile: Dockerfile
    image: gcr.io/elegant-fort-344208/order:v1
    restart: always
    ports:
      - "5000:5000"
    labels:
      kompose.service.type: LoadBalancer
      kompose.service.group: stock-order

  # ###################################
  # # Payment: The Payment microservice
  # ###################################
  payment:
    build:
      context: ./app/payment_service
      dockerfile: Dockerfile
    image: gcr.io/elegant-fort-344208/payment:v1
    restart: always
    ports:
      - "4242:4242"
    labels:
      kompose.service.type: LoadBalancer

  ###############################################
  # Stock: The Stock microservice
  ###############################################
  stock:
    build:
      context: ./app/stock_service
      dockerfile: Dockerfile
    image: gcr.io/elegant-fort-344208/stock:v1
    restart: always
    ports:
      - "5001:5001"
    labels:
      kompose.service.type: LoadBalancer
      kompose.service.group: stock-order

  ##################################
  # Users: The Users microservice
  ##################################
  users:
    build:
      context: ./app/users_service
      dockerfile: Dockerfile
    image: gcr.io/elegant-fort-344208/users:v1
    restart: always
    ports:
      - "5003:5003"
    labels:
      kompose.service.type: LoadBalancer

