apiVersion: v1
kind: Service
metadata:
  labels:
    name: order
  name: order
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    name: order
  type: LoadBalancer
status:
  loadBalancer: {}
