apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: order
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      name: order
  strategy: {}
  template:
    metadata:
      labels:
        name: order
    spec:
      containers:
        - image: gcr.io/elegant-fort-344208/order:v1
          name: order
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
