apiVersion: v1
kind: Service
metadata:
  labels:
    name: payment 
  name: payment
spec:
  ports:
    - name: "4242"
      port: 4242
      targetPort: 4242
  selector:
    name: payment
  type: LoadBalancer
status:
  loadBalancer: {}
