apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: payment
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: payment
  strategy: {}
  template:
    metadata:
      labels:
        name: payment
    spec:
      containers:
        - image: gcr.io/elegant-fort-344208/payment:v1
          name: payment
          ports:
            - containerPort: 4242
          resources: {}
      restartPolicy: Always
status: {}
