apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: product
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      name: product
  strategy: {}
  template:
    metadata:
      labels:
        name: product 
    spec:
      containers:
        - image: gcr.io/elegant-fort-344208/product:v1
          name: product
          ports:
            - containerPort: 5005
          resources: {}
      restartPolicy: Always
status: {}
