apiVersion: v1
kind: Service
metadata:
  labels:
    name: product
  name: product
spec:
  ports:
    - name: "5005"
      port: 5005
      targetPort: 5005
  selector:
    name: product
  type: LoadBalancer
status:
  loadBalancer: {}
