apiVersion: v1
kind: Service
metadata:
  # annotations:
  #   kompose.cmd: C:\Users\lingl\OneDrive\Documents\GitHub\cloud-mgmt\kompose.exe convert
  #   kompose.service.type: LoadBalancer
  #   kompose.version: 1.26.0 (40646f47)
  # creationTimestamp: null
  labels:
    # io.kompose.service: product-tcp
    name: product
  # name: product-tcp
  name: product
spec:
  ports:
    - name: "5005"
      port: 5005
      targetPort: 5005
  selector:
    # io.kompose.service: product
    name: product
  type: LoadBalancer
status:
  loadBalancer: {}
