apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: stock
  name: stock
spec:
  replicas: 1
  selector:
    matchLabels:
      name: stock
  strategy: {}
  template:
    metadata:
      labels:
        name: stock
    spec:
      containers:
        - image: gcr.io/elegant-fort-344208/stock:v1
          name: stock
          ports:
            - containerPort: 5001
          resources: {}
      restartPolicy: Always
status: {}
