apiVersion: v1
kind: Service
metadata:
  labels:
    name: stock
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    name: stock
  type: LoadBalancer
status:
  loadBalancer: {}
