apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
  #   kompose.cmd: C:\Users\lingl\OneDrive\Documents\GitHub\cloud-mgmt\kompose.exe convert
  #   kompose.service.type: LoadBalancer
  #   kompose.version: 1.26.0 (40646f47)
  # creationTimestamp: null
  labels:
    label: users 
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      # io.kompose.service: users
      label: users 
  strategy: {}
  template:
    metadata:
      # annotations:
      #   kompose.cmd: C:\Users\lingl\OneDrive\Documents\GitHub\cloud-mgmt\kompose.exe convert
      #   kompose.service.type: LoadBalancer
      #   kompose.version: 1.26.0 (40646f47)
      # creationTimestamp: null
      labels:
        # io.kompose.service: users
        label: users 
    spec:
      containers:
        - name: users
            # - name: DBNAME
            # - name: INSTANCE_NAME
            # - name: PASSWORD
            # - name: PROJECT_ID
            # - name: PUBLIC_IP_ADDRESS
            # - name: PYTHONUNBUFFERED
            #   value: "1"
          image: gcr.io/elegant-fort-344208/users:v1
          ports:
            - containerPort: 5003
          resources: {}
      restartPolicy: Always
status: {}
