apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
  #   kompose.cmd: C:\Users\lingl\OneDrive\Documents\GitHub\cloud-mgmt\kompose.exe convert
  #   kompose.service.type: LoadBalancer
  #   kompose.version: 1.26.0 (40646f47)
  # creationTimestamp: null
  labels:
    # io.kompose.service: users
    name: users
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      # io.kompose.service: users
      name: users
  strategy: {}
  template:
    metadata:
      # annotations:
      #   kompose.cmd: C:\Users\lingl\OneDrive\Documents\GitHub\cloud-mgmt\kompose.exe convert
      #   kompose.service.type: LoadBalancer
      #   kompose.version: 1.26.0 (40646f47)
      # creationTimestamp: null
      labels:
        # io.kompose.service: users
        name: users
    spec:
      containers:
        - image: gcr.io/elegant-fort-344208/users:v1
          name: users
          ports:
            - containerPort: 5003
          resources: {}
      restartPolicy: Always
status: {}
