apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: users
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: users
    spec:
      containers:
        - env:
            - name: DBNAME
            - name: INSTANCE_NAME
            - name: PASSWORD
            - name: PROJECT_ID
            - name: PUBLIC_IP_ADDRESS
            - name: PYTHONUNBUFFERED
              value: "1"
          image: lingliyin/users:v1
          name: users
          ports:
            - containerPort: 5003
          resources: {}
      restartPolicy: Always
status: {}
