apiVersion: v1
kind: Service
metadata:
  labels:
    app: cart
  name: cart-lb
  annotations: 
    beta.cloud.google.com/backend-config: '{"ports": {"http":"cloud-armor"}}
spec:
  type: LoadBalancer
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006