apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-backend
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /product/*
        pathType: Prefix
        backend:
          service:
            name: product-lb
            port:
              number: 5005
      - path: /cart/*
        pathType: Prefix
        backend:
          service:
            name: cart-lb
            port:
              number: 5006