apiVersion: v1
kind: Service
metadata:
  labels:
    app: product
  name: product-lb
spec:
  type: ClusterIP
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005