# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: users
#   name: users-lb
# spec:
#   type: LoadBalancer 
#   selector:
#     app: users
#   ports:
#     - protocol: TCP
#       port: 5003
#       targetPort: 5003

apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  type: NodePort
  selector:
    greeting: hello
    version: one
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 50000