# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: users
#   name: users-service
# spec:
#   type: NodePort 
#   selector:
#     app: users
#   ports:
#     - protocol: TCP
#       port: 60000
#       targetPort: 5003

apiVersion: v1
kind: Service
metadata:
  name: users
  labels:
    greeting: hello 
    version: one 
spec:
  type: NodePort
  selector:
    labels: 
      greeting: hello
      version: one
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 50000


