apiVersion: v1
kind: Service
metadata:
  labels:
    greeting: hello 
  name: users-service
spec:
  type: NodePort 
  selector:
    greeting: users 
  ports:
    - protocol: TCP
      port: 60000
      targetPort: 5003

# apiVersion: v1
# kind: Service
# metadata:
#   name: users
#   labels:
#     greeting: hello 
# spec:
#   type: NodePort
#   selector:
#     labels: 
#       greeting: hello
#   ports:
#   - protocol: TCP
#     port: 60000
#     targetPort: 50000


