name: Build and Deploy to GKE

on:
  push:
    branches:
      - main 

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: clae-gke   # Add your cluster name here.
  GKE_ZONE: asia-southeast1-b   # Add your cluster zone here.

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy to GKE 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
  

    # Build the Docker images
    - name: Build Core Services 
      run: |-
        docker-compose -f ./docker-compose.yml build   
        ls -a 

    - name: Build Stock Pub/Sub 
      working-directory: ./app/stock_subscriber
      run: |- 
        docker build . -f Dockerfile -t gcr.io/elegant-fort-344208/stock-pubsub:v1
    
    - name: Build Order Pub/Sub 
      working-directory: ./app/order_subscriber 
      run: |-
        docker build . -f Dockerfile -t gcr.io/elegant-fort-344208/order-pubsub:v1

    # Push the Docker images to Google Container Registry
    - name: Publish
      run: |-
        gcloud docker -- push gcr.io/$PROJECT_ID/product:v1
        gcloud docker -- push gcr.io/$PROJECT_ID/users:v1
        gcloud docker -- push gcr.io/$PROJECT_ID/payment:v1
        gcloud docker -- push gcr.io/$PROJECT_ID/cart:v1
        gcloud docker -- push gcr.io/$PROJECT_ID/order:v1
        gcloud docker -- push gcr.io/$PROJECT_ID/stock:v1
        gcloud docker -- push gcr.io/$PROJECT_ID/order-pubsub:v1
        gcloud docker -- push gcr.io/$PROJECT_ID/stock-pubsub:v1

    # Apply Kubernetes Cluster based on Manifest files 
    - name: Deploy
      run: |-
        kubectl apply -f ./gke_config/product.yaml -f ./gke_config/product-service.yaml -f ./gke_config/users.yaml -f ./gke_config/users-service.yaml -f ./gke_config/payment.yaml -f ./gke_config/payment-service.yaml -f ./gke_config/cart.yaml -f ./gke_config/cart-service.yaml -f ./gke_config/order.yaml -f ./gke_config/order-service.yaml -f ./gke_config/stock.yaml -f ./gke_config/stock-service.yaml -f ./gke_config/order-pubsub.yaml ./gke_config/order-pubsub-service.yaml -f ./gke_config/stock-pubsub.yaml -f ./gke_config/stock-pubsub-service.yaml 
        kubectl rollout status deployment/product
        kubectl rollout status deployment/users
        kubectl rollout status deployment/payment
        kubectl rollout status deployment/cart
        kubectl rollout status deployment/order 
        kubectl rollout status deployment/stock
        kubectl rollout status deployment/order-pubsub
        kubectl rollout status deployment/stock-pubsub
        kubectl get services -o wide