# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: clae2    # Add your cluster name here.
  GKE_ZONE: asia-east1-c   # Add your cluster zone here.

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Build the Docker images
    - name: Build
      run: |-
        docker-compose -f ./docker-compose.yml build 

    # Push the Docker images to Google Container Registry
    - name: Publish
      run: |-
        gcloud docker -- push gcr.io/$PROJECT_ID/product:v1
        gcloud docker -- push gcr.io/$PROJECT_ID/cart:v1
        gcloud docker -- push gcr.io/$PROJECT_ID/order:v1
        gcloud docker -- push gcr.io/$PROJECT_ID/payment:v1
        gcloud docker -- push gcr.io/$PROJECT_ID/stock:v1
        gcloud docker -- push gcr.io/$PROJECT_ID/users:v1

    # Set up Kompose 
    - name: Set up Kompose
      run: |-
        curl -L https://github.com/kubernetes/kompose/releases/download/v1.26.0/kompose-linux-amd64 -o kompose

    - name: Set up Kompose Permissions 
      run: |-
        chmod +x kompose
        sudo mv ./kompose /usr/local/bin/kompose

    # Deploy the Docker images to the GKE cluster
    - name: Deploy
      run: |-
        kompose convert 
        kubectl apply -f ./cart-service.yaml -f ./order-service.yaml -f ./payment-service.yaml -f ./payment-service.yaml -f ./product-service.yaml -f ./stock-service.yaml -f ./users-service.yaml -f ./cart-deployment.yaml -f ./order-deployment.yaml -f ./payment-deployment.yaml -f ./product-deployment.yaml -f ./stock-deployment.yaml -f ./users-deployment.yaml
        kubectl rollout status deployment.apps/cart 
        kubectl rollout status deployment.apps/order
        kubectl rollout status deployment.apps/payment
        kubectl rollout status deployment.apps/product
        kubectl rollout status deployment.apps/stock
        kubectl rollout status deployment.apps/users  
        kubectl get services -o wide